# Generated by Django 3.2.13 on 2023-05-21 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Верификация'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(unique=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('expiration', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
