# Generated by Django 3.2.13 on 2023-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230521_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_verified_email',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Верификация'),
        ),
    ]
