# Generated by Django 3.2.13 on 2023-05-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='statuses',
            new_name='status',
        ),
    ]
